// GENERATED FILE — do not hand-edit.
// Run `pnpm --filter @werf/sync generate:schema` to regenerate from the Postgres schema and
// the TENANCY registry (scripts/derive-local-schema.ts). test/local-schema-freshness.spec.ts
// fails the build if this drifts from what that derivation produces.

import type { LocalTableDef } from './local-schema';

export const LOCAL_SCHEMA_TABLES: readonly LocalTableDef[] = [
  {
    name: 'animal_identifiers',
    columns: [
      { name: 'animal_id', type: 'TEXT' },
      { name: 'applied_at', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'is_primary', type: 'INTEGER' },
      { name: 'type', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
      { name: 'value', type: 'TEXT' },
    ],
  },
  {
    name: 'animals',
    columns: [
      { name: 'acquired_at', type: 'TEXT' },
      { name: 'attributes', type: 'TEXT' },
      { name: 'brand_applied_at', type: 'TEXT' },
      { name: 'brand_id', type: 'TEXT' },
      { name: 'breed', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'dam_id', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'dob', type: 'TEXT' },
      { name: 'dob_estimated', type: 'INTEGER' },
      { name: 'enterprise_id', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'land_unit_id', type: 'TEXT' },
      { name: 'mob_id', type: 'TEXT' },
      { name: 'photo_key', type: 'TEXT' },
      { name: 'sex', type: 'TEXT' },
      { name: 'sire_id', type: 'TEXT' },
      { name: 'source', type: 'TEXT' },
      { name: 'species', type: 'TEXT' },
      { name: 'status', type: 'TEXT' },
      { name: 'status_at', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'attachments',
    columns: [
      { name: 'checksum', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'mime_type', type: 'TEXT' },
      { name: 'object_key', type: 'TEXT' },
      { name: 'occurred_at', type: 'TEXT' },
      { name: 'size_bytes', type: 'INTEGER' },
      { name: 'status', type: 'TEXT' },
      { name: 'subject_id', type: 'TEXT' },
      { name: 'subject_type', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'branding_registers',
    columns: [
      { name: 'body_position', type: 'TEXT' },
      { name: 'certificate_reference', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'jurisdiction', type: 'TEXT' },
      { name: 'mark', type: 'TEXT' },
      { name: 'mark_type', type: 'TEXT' },
      { name: 'registered_at', type: 'TEXT' },
      { name: 'species', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'businesses',
    columns: [
      { name: 'created_at', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'registration_number', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'vat_number', type: 'TEXT' },
    ],
  },
  {
    name: 'chemical_products',
    columns: [
      { name: 'active_ingredients', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'crop', type: 'TEXT' },
      { name: 'effective_from', type: 'TEXT' },
      { name: 'effective_to', type: 'TEXT' },
      { name: 'jurisdiction', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'phi_days', type: 'INTEGER' },
      { name: 'reentry_hours', type: 'INTEGER' },
      { name: 'registration_number', type: 'TEXT' },
      { name: 'version', type: 'INTEGER' },
    ],
  },
  {
    name: 'enterprises',
    columns: [
      { name: 'active', type: 'INTEGER' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'type', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
    ],
  },
  {
    name: 'events',
    columns: [
      { name: 'animal_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'employee_id', type: 'TEXT' },
      { name: 'enterprise_id', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'inventory_lot_id', type: 'TEXT' },
      { name: 'land_unit_id', type: 'TEXT' },
      { name: 'location_geojson', type: 'TEXT' },
      { name: 'mob_id', type: 'TEXT' },
      { name: 'notes', type: 'TEXT' },
      { name: 'occurred_at', type: 'TEXT' },
      { name: 'payload', type: 'TEXT' },
      { name: 'synced_at', type: 'TEXT' },
      { name: 'type', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
    ],
  },
  {
    name: 'farm_users',
    columns: [
      { name: 'accepted_at', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'expires_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'invited_at', type: 'TEXT' },
      { name: 'role', type: 'TEXT' },
      { name: 'scope', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT' },
    ],
  },
  {
    name: 'farms',
    columns: [
      { name: 'attachment_bytes_used', type: 'INTEGER' },
      { name: 'business_id', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'district', type: 'TEXT' },
      { name: 'enterprise_types', type: 'TEXT' },
      { name: 'event_retention_months', type: 'INTEGER' },
      { name: 'hectares', type: 'REAL' },
      { name: 'jurisdiction', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'province', type: 'TEXT' },
      { name: 'rest_period_days', type: 'INTEGER' },
      { name: 'timezone', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
    ],
  },
  {
    name: 'inventory_items',
    columns: [
      { name: 'active_ingredients', type: 'TEXT' },
      { name: 'category', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'enterprise_id', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'meat_withdrawal_days', type: 'INTEGER' },
      { name: 'milk_withdrawal_hours', type: 'INTEGER' },
      { name: 'name', type: 'TEXT' },
      { name: 'phi_days', type: 'INTEGER' },
      { name: 'reentry_hours', type: 'INTEGER' },
      { name: 'registration_number', type: 'TEXT' },
      { name: 'reorder_point', type: 'REAL' },
      { name: 'unit', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'inventory_lots',
    columns: [
      { name: 'batch', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'expiry_date', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'inventory_item_id', type: 'TEXT' },
      { name: 'location', type: 'TEXT' },
      { name: 'quantity_on_hand', type: 'REAL' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'land_units',
    columns: [
      { name: 'attributes', type: 'TEXT' },
      { name: 'boundary_geojson', type: 'TEXT' },
      { name: 'carrying_capacity_lsu', type: 'REAL' },
      { name: 'code', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'enterprise_id', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'hectares', type: 'REAL' },
      { name: 'irrigation', type: 'TEXT' },
      { name: 'kind', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'parent_id', type: 'TEXT' },
      { name: 'soil_type', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'mobs',
    columns: [
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'enterprise_id', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'head_count', type: 'INTEGER' },
      { name: 'initial_head_count', type: 'INTEGER' },
      { name: 'land_unit_id', type: 'TEXT' },
      { name: 'name', type: 'TEXT' },
      { name: 'species', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'regulatory_rates',
    columns: [
      { name: 'code', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'effective_from', type: 'TEXT' },
      { name: 'effective_to', type: 'TEXT' },
      { name: 'gazette_reference', type: 'TEXT' },
      { name: 'jurisdiction', type: 'TEXT' },
      { name: 'notes', type: 'TEXT' },
      { name: 'unit', type: 'TEXT' },
      { name: 'value', type: 'REAL' },
    ],
  },
  {
    name: 'species_gestation',
    columns: [
      { name: 'created_at', type: 'TEXT' },
      { name: 'gestation_days', type: 'INTEGER' },
      { name: 'source', type: 'TEXT' },
      { name: 'species', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
    ],
  },
  {
    name: 'theft_incident_animals',
    columns: [
      { name: 'animal_id', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'incident_id', type: 'TEXT' },
      { name: 'recovered_at', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'theft_incidents',
    columns: [
      { name: 'case_number', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'discovered_at', type: 'TEXT' },
      { name: 'evidence_pack_key', type: 'TEXT' },
      { name: 'farm_id', type: 'TEXT' },
      { name: 'head_count', type: 'INTEGER' },
      { name: 'land_unit_id', type: 'TEXT' },
      { name: 'last_seen_at', type: 'TEXT' },
      { name: 'last_seen_location_geojson', type: 'TEXT' },
      { name: 'observations', type: 'TEXT' },
      { name: 'reporting_station', type: 'TEXT' },
      { name: 'status', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
      { name: 'updated_by', type: 'TEXT' },
    ],
  },
  {
    name: 'users',
    columns: [
      { name: 'created_at', type: 'TEXT' },
      { name: 'deleted_at', type: 'TEXT' },
      { name: 'email', type: 'TEXT' },
      { name: 'full_name', type: 'TEXT' },
      { name: 'last_seen_at', type: 'TEXT' },
      { name: 'locale', type: 'TEXT' },
      { name: 'phone', type: 'TEXT' },
      { name: 'theme', type: 'TEXT' },
      { name: 'updated_at', type: 'TEXT' },
    ],
  },
  {
    name: 'veterinary_products',
    columns: [
      { name: 'active_ingredients', type: 'TEXT' },
      { name: 'created_at', type: 'TEXT' },
      { name: 'dose_per_kg', type: 'REAL' },
      { name: 'effective_from', type: 'TEXT' },
      { name: 'effective_to', type: 'TEXT' },
      { name: 'jurisdiction', type: 'TEXT' },
      { name: 'meat_withdrawal_days', type: 'INTEGER' },
      { name: 'milk_withdrawal_hours', type: 'INTEGER' },
      { name: 'name', type: 'TEXT' },
      { name: 'registration_number', type: 'TEXT' },
      { name: 'route', type: 'TEXT' },
      { name: 'species', type: 'TEXT' },
      { name: 'version', type: 'INTEGER' },
    ],
  },
];
